[package]
name = "cif-parser"
version = "0.1.0"
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
edition = "2018"

[dependencies]
nom = "5.0.0"
structopt = "0.2.18"
memmap = "0.7.0"
failure = "0.1.5"
log = "0.4.7"
env_logger = "0.7.1"

smallstr = "0.1.0"
smallvec = "0.6.10"
chrono = "0.4.7"
lexical-core = "0.5.0"
chrono-tz = "0.5.1"
bitflags = "1.1.0"

[profile.release]
debug = true
