[package]
name = "cif-parser"
version = "0.1.0"
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
edition = "2018"

[dependencies]
nom = "5.0.0"
structopt = "0.3.15"
log = "0.4.7"
env_logger = "0.7.1"

chrono = "0.4.7"
lexical-core = "0.7.4"
chrono-tz = "0.5.1"
bitflags = "1.1.0"
anyhow = "1.0.31"
suppositions = { git = "https://github.com/cstorey/suppositions.git" }
bytes = "0.5.5"

[profile.release]
debug = true
