# Borrowed from https://github.com/sfackler/rust-postgres/blob/04bd98e7edb238511661b311c725a176012bca6a/.circleci/config.yml
# Used under MIT license.

version: 2.1
jobs:
  buildtest:
    docker:
      - image: cimg/rust:1.65
        environment:
          RUSTFLAGS: -D warnings
    steps:
      - checkout
      - run: |
          upstream=${CIRCLE_REPOSITORY_URL:-$(git remote  get-url origin)}
          git config --global user.email "circleci@invalid.example"
          git config --global user.name "CircleCI build for ${upstream}"
          git merge main --no-edit
      - run: rustup component add rustfmt
      - run: rustfmt --version
      - run: cargo fmt --all -- --check
      - run: rustc --version | tee ~/rust-version
      - run: cargo build --all --tests --all-features
      - run: cargo test --all --all-features
workflows:
  testall:
    jobs:
      - buildtest
